/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.interfaces.DAOEmpleado;
import com.mycompany.interfaces.DAOVeterinario;
import com.mycompany.models.DAOEmpleadoImplements;
import com.mycompany.models.DAOVeterinarioImplements;
import com.mycompany.models.Empleado;
import com.mycompany.models.Veterinario;
import com.mycompany.utils.pagination.EventPagination;
import com.mycompany.utils.pagination.style.PaginationItemRenderStyle1;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 52951
 */
public class EmployeeAdmin extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeAdmin
     */
    public EmployeeAdmin() {
        initComponents();
        LoadEmployee();
        pgnPagination.setPaginationItemRender(new PaginationItemRenderStyle1());
        pgnPagination.addEventPagination(new EventPagination() {
            @Override
            public void pageChanged(int page) {
                LoadEmployee();
            }
        });
    }

    private void LoadEmployee( ) {
        try {
            DAOVeterinario dao = new DAOVeterinarioImplements();
            DefaultTableModel model = (DefaultTableModel) tblTable.getModel();
            tblTable.removeAll();
          
            dao.listar("", "", 0, 0).forEach((u) -> model.addRow(new Object[]{u.getNombre(), u.getCorreo(), "Veterinario"}));
            DAOEmpleado daoEmp = new DAOEmpleadoImplements();
            daoEmp.listar(txtSearch.getText(), "", 0, 0).forEach((u) -> model.addRow(new Object[]{u.getNombre(), u.getCorreo(), u.getRol()}));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        pgnPagination = new com.mycompany.utils.pagination.Pagination();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTable = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnAlter = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        pgnPagination.setOpaque(false);

        jLabel1.setText("Empleados");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        tblTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Correo", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTable);

        btnAdd.setText("Agregar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnAlter.setText("Modificar");
        btnAlter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterActionPerformed(evt);
            }
        });

        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(pgnPagination, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlter)
                        .addGap(64, 64, 64))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pgnPagination, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAlter)
                            .addComponent(btnAdd)
                            .addComponent(btnDelete))
                        .addGap(10, 10, 10)))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String valor = (String) tblTable.getValueAt(tblTable.getSelectedRow(), 2);
        DefaultTableModel model = (DefaultTableModel) tblTable.getModel();
        if (tblTable.getSelectedRows().length < 1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar uno o más usuarios a eliminar.\n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
            if ("Veterinario".equals(valor)) {
                for (int i : tblTable.getSelectedRows()) {
                    try {
                        DAOVeterinario dao = new DAOVeterinarioImplements();
                        String nombre = (String) tblTable.getValueAt(tblTable.getSelectedRow(), 0);
                       
                        Veterinario vet = new Veterinario(nombre, "", "");
                        dao.eliminar(vet.getNombre_usuario());
                        model.removeRow(i);
                    } catch (Exception e) {
                        System.out.println(e.getMessage());
                    }
                }

            } else if(valor.toLowerCase().equals("admin") || valor.toLowerCase().equals("empleado")){
                for (int i : tblTable.getSelectedRows()) {
                    try {
                        DAOEmpleado dao = new DAOEmpleadoImplements();
                        String nombre = (String) tblTable.getValueAt(tblTable.getSelectedRow(), 0);
                        
                        Empleado emp = new Empleado(nombre, "", valor, "");
                        dao.eliminar(emp.getNombre_usuario());
                        model.removeRow(i);
                    } catch (Exception e) {
                        System.out.println(e.getMessage());
                    }
                }
            }

        }
        

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAlterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterActionPerformed
        // TODO add your handling code here:
        
        String valor = (String) tblTable.getValueAt(tblTable.getSelectedRow(), 2);
        tblTable.removeAll();
        if ("Veterinario".equals(valor)) {
            String nombre = (String) tblTable.getValueAt(tblTable.getSelectedRow(), 0);
             int fila = tblTable.getSelectedRow();
             String correo = (String) tblTable.getValueAt(fila, 1);
             String rol = (String) tblTable.getValueAt(fila, 2);
             
             Veterinario vet= new Veterinario (nombre,correo,"password");
             new FormRegister(null, vet).setVisible(true);
        
        }else{
            String nombre = (String) tblTable.getValueAt(tblTable.getSelectedRow(), 0);
             int fila = tblTable.getSelectedRow();
             String correo = (String) tblTable.getValueAt(fila, 1);
             String rol = (String) tblTable.getValueAt(fila, 2);
             
             Empleado emp= new Empleado (nombre,correo,rol,"password");
             new FormRegister(emp, null).setVisible(true);
             
        }
        LoadEmployee();
        
    }//GEN-LAST:event_btnAlterActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        tblTable.removeAll();
        new FormRegister().setVisible(true);
         LoadEmployee();
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        // TODO add your handling code here:
        try {
            tblTable.removeAll();
            DAOVeterinario dao = new DAOVeterinarioImplements();
            DefaultTableModel model = (DefaultTableModel) tblTable.getModel();
            model.setRowCount(0);
            dao.listar(txtSearch.getText(), "", 0, 0).forEach((u) -> model.addRow(new Object[]{u.getNombre(), u.getCorreo(), "Veterinario"}));
            DAOEmpleado daoEmp = new DAOEmpleadoImplements();
            daoEmp.listar(txtSearch.getText(), "", 0, 0).forEach((u) -> model.addRow(new Object[]{u.getNombre(), u.getCorreo(), u.getRol()}));

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_txtSearchKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAlter;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private com.mycompany.utils.pagination.Pagination pgnPagination;
    private javax.swing.JTable tblTable;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
