/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.views;

import com.mycompany.interfaces.DAOEmpleado;
import com.mycompany.interfaces.DAOVeterinario;
import com.mycompany.models.DAOEmpleadoImplements;
import com.mycompany.models.DAOVeterinarioImplements;
import com.mycompany.models.Empleado;
import com.mycompany.models.Veterinario;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 52951
 */
public class FromLogin extends javax.swing.JFrame {

    /**
     * Creates new form FromLogin
     */
    public FromLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSubtitle2 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblShow = new javax.swing.JLabel();
        btnLog = new javax.swing.JButton();
        cbxUser = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSubtitle2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblSubtitle2.setText("Ingrese usuario y contraseña");
        jPanel1.add(lblSubtitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 270, 40));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setText("VETERINARIA");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 230, 40));

        lblSubtitle1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblSubtitle1.setText("Inicio de Sesion");
        jPanel1.add(lblSubtitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 170, 40));

        txtUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUser.setForeground(new java.awt.Color(204, 204, 204));
        txtUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUser.setText("Usuario");
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUserMousePressed(evt);
            }
        });
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 300, 40));

        txtPassword.setForeground(new java.awt.Color(204, 204, 204));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setText("contraseña");
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPasswordMousePressed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 300, 40));

        lblShow.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblShow.setText("Mostrar");
        lblShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblShowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblShowMouseExited(evt);
            }
        });
        jPanel1.add(lblShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        btnLog.setBackground(new java.awt.Color(0, 0, 0));
        btnLog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLog.setForeground(new java.awt.Color(255, 255, 255));
        btnLog.setText("Iniciar Sesion");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });
        jPanel1.add(btnLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 360, 40));

        cbxUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Veterinario", "Administrador" }));
        jPanel1.add(cbxUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblShowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowMouseEntered
        // TODO add your handling code here:
        txtPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_lblShowMouseEntered

    private void lblShowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowMouseExited
        // TODO add your handling code here:
        txtPassword.setEchoChar('*');
    }//GEN-LAST:event_lblShowMouseExited

    private void txtUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMousePressed
        // TODO add your handling code here:
        if (txtUser.getText().equals("Usuario")) {
            txtUser.setText("");
            txtUser.setForeground(Color.GRAY);
        } else {
            txtUser.setForeground(Color.BLACK);
        }
        if (String.valueOf(txtPassword.getPassword()).isEmpty()) {
            txtPassword.setText("contraseña");
            txtPassword.setForeground(Color.GRAY);
        } else {
            txtPassword.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtUserMousePressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtPasswordKeyPressed

    private void txtPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMousePressed
        // TODO add your handling code here:
        if (String.valueOf(txtPassword.getPassword()).equals("contraseña")) {
            txtPassword.setText("");
            txtPassword.setForeground(Color.BLACK);
        } else {
            txtPassword.setForeground(Color.BLACK);
        }
        if (txtUser.getText().isEmpty()) {
            txtUser.setText("Usuario");
        } else {
            txtUser.setForeground(Color.BLACK);
        }

    }//GEN-LAST:event_txtPasswordMousePressed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        // TODO add your handling code here:{\\\
        if (new String(txtPassword.getPassword()).isEmpty() || txtUser.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, """
                                                                        Debes ingresar datos
                                                                        No se puede acceder sin ingresar usuario y contraseña""", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;

        } else {
            //empleado, veterinario, administrador
            switch (cbxUser.getSelectedIndex()) {
                case 0:
                    DAOEmpleado dao = new DAOEmpleadoImplements();
                     {
                        try {
                            List<Empleado> emps = dao.listar("", txtUser.getText(), 0, 0);
                            if (emps.isEmpty()) {
                                javax.swing.JOptionPane.showMessageDialog(this, """
                                                                        Debes ingresar datos correctos
                                                                        No se puede acceder el usuario es incorrecto""", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                return;
                            }
                            Empleado emp = emps.get(0);
                            if (!new String(txtPassword.getPassword()).equals(emp.getContraseña())) {
                                javax.swing.JOptionPane.showMessageDialog(this, """
                                                                        Debes ingresar datos correctos
                                                                        No se puede acceder la contraseña es incorrecta""", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                return;

                            }
                            if (emp.getRol().equals("empleado")) {
                                this.setVisible(false);
                                new DashboardEmployee().setVisible(true);
                            } else {
                                javax.swing.JOptionPane.showMessageDialog(this, """
                                                                        Debes ingresar datos correctos
                                                                        Tu usuario fue encontrado, pero los permisos no coinciden""", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                return;
                            }
                        } catch (Exception ex) {
                            Logger.getLogger(FromLogin.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                    break;

                case 1:
                    DAOVeterinario daovet = new DAOVeterinarioImplements();

                     {
                        try {
                            List<Veterinario> lista = daovet.listar("", txtUser.getText(), 0, 0);
                            if (lista.isEmpty()) {
                                javax.swing.JOptionPane.showMessageDialog(this, """
                                                                        Debes ingresar datos correctos
                                                                        No se puede acceder el usuario es incorrecto""", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                return;
                            }
                            Veterinario vet = lista.get(0);
                            if (!new String(txtPassword.getPassword()).equals(vet.getContraseña())) {
                                javax.swing.JOptionPane.showMessageDialog(this, """
                                                                        Debes ingresar datos correctos
                                                                        No se puede acceder la contraseña es incorrecta""", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                return;

                            }
                            this.setVisible(false);
                            new  DashboardVeterinarian().setVisible(true);
                        } catch (Exception ex) {
                            Logger.getLogger(FromLogin.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    break;

                case 2:
                    dao = new DAOEmpleadoImplements();
                     {
                        try {
                            List<Empleado> emps = dao.listar("", txtUser.getText(), 0, 0);
                            if (emps.isEmpty()) {
                                javax.swing.JOptionPane.showMessageDialog(this, """
                                                                        Debes ingresar datos correctos
                                                                        No se puede acceder el usuario es incorrecto""", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                return;
                            }
                            Empleado emp = emps.get(0);
                            if (!new String(txtPassword.getPassword()).equals(emp.getContraseña())) {
                                javax.swing.JOptionPane.showMessageDialog(this, """
                                                                        Debes ingresar datos correctos
                                                                        No se puede acceder la contraseña es incorrecta""", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                return;

                            }
                            if (emp.getRol().equals("admin")) {
                                this.setVisible(false);
                                new DashboardAdmin().setVisible(true);
                            }
                        } catch (Exception ex) {
                            Logger.getLogger(FromLogin.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    break;
                default:
                    break;
            }
        }

    }//GEN-LAST:event_btnLogActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLog;
    private javax.swing.JComboBox<String> cbxUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblShow;
    private javax.swing.JLabel lblSubtitle1;
    private javax.swing.JLabel lblSubtitle2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
